// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uJsQEdZ2Gl3pPBQ-1RBP9JP3HUbLGks',
    appId: '1:503683626836:web:8995c640d19e64d246fac1',
    messagingSenderId: '503683626836',
    projectId: 'zzsample',
    authDomain: 'zzsample.firebaseapp.com',
    storageBucket: 'zzsample.appspot.com',
    measurementId: 'G-Y7B8E06YQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEYDPxOTDVlm5ag10PE24yN3mz_g9q0aE',
    appId: '1:503683626836:android:54d8c92698314b2546fac1',
    messagingSenderId: '503683626836',
    projectId: 'zzsample',
    storageBucket: 'zzsample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKI5dKYuB18fY89Xb3Ohm5CZnTUctf6QI',
    appId: '1:503683626836:ios:e0f46a8facfaa6d646fac1',
    messagingSenderId: '503683626836',
    projectId: 'zzsample',
    storageBucket: 'zzsample.appspot.com',
    iosClientId: '503683626836-5ka3kkhv6b6v83vvgmqr16vvvnls9992.apps.googleusercontent.com',
    iosBundleId: 'com.example.widgetSample',
  );
}
